### ISSUE TITLE
Product Categories with multiple tags aren't displayed in the marketplace

### ISSUE THREAD

**Issue by AnkyrinRepeat** [projectjellyfish/api#1123] opened 2015-12-28 20:42 UTC
Any product category with multiple tags is not displayed, an example of this in the demo data is the Storage product category that has the storage and cdn tag.

**Comment by stackus** [comment] 2015-12-28 22:18
This is working as intended. Closing as a duplicate of #1049

**Closed by stackus** 2015-12-28 22:18 UTC
Labels: bug
