### ISSUE TITLE
Need admin UX to CRUD MotD message on login screen

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#397] opened 2015-03-27 00:06 UTC
Need admin UX to CRUD MotD message on login screen

**Comment by chriskacerguis** [comment] 2015-03-27 00:06
<a href="https://github.com/chriskacerguis"><img src="https://avatars.githubusercontent.com/u/2414647?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chriskacerguis](https://github.com/chriskacerguis)**
_Thursday Feb 12, 2015 at 19:50 GMT_

----

Tied to: https://github.com/projectjellyfish/ux/issues/130

**Comment by AllenBW** [comment] 2015-06-30 13:13
lets talk about where to put this! under admin settings (on the left?) or
settings under the user?  (when you click on their icon)

**Comment by chriskacerguis** [comment] 2015-06-30 13:14
I would put this under the admin settings.

**Comment by AllenBW** [comment] 2015-06-30 16:02
dupe of #388, its crud is implied

**Closed by AllenBW** 2015-06-30 16:02 UTC
Labels: feature, ux
