### ISSUE TITLE
Alerts layout needs slight adjustment

### ISSUE THREAD

**Issue by OBCENEIKON** [projectjellyfish/api#750] opened 2015-06-16 18:44 UTC
When attempting to save an alert without filling in all required fields this happens.

![image](https://cloud.githubusercontent.com/assets/164630/8191470/ca667f4a-142d-11e5-8b39-35888f438a1e.png)

**Comment by AllenBW** [comment] 2015-06-16 19:30
dupe of #734

**Closed by AllenBW** 2015-06-16 19:30 UTC
