### ISSUE TITLE
Deploy to Heroku broken ?

### ISSUE THREAD

**Issue by LudovicBethune** [projectjellyfish/api#884] opened 2015-07-29 11:34 UTC
I'm trying to deploy on heroku using the github link deploy to heroku, all the build seems to work fine on heroku, but, when i go to the home, i have a Status Code:500 Internal Server Error.
Is the "deploy to heroku" still available to test Projectjellyfish ?

**Comment by chriskacerguis** [comment] 2015-07-29 15:46
Hmmm...looks like the issue is that it's not running gulp build.  Investigating.

**Comment by AllenBW** [comment] 2015-07-29 15:48
ooh ooh i totally know the answer to this one. we have a new dependency,
bower dependency, need to do bower install before gulp build

**Comment by chriskacerguis** [comment] 2015-07-29 16:40
@stackus can you verify this is working?

**Comment by chriskacerguis** [comment] 2015-07-29 16:41
the push to heroku butting?  I'm thinking we need to add a post deploy step for "gulp build" in the app.json file??

**Comment by stackus** [comment] 2015-07-29 20:56
Deployment definition used for Heroku Deploy button has been updated. Button works again.

Resolved in #887

**Closed by stackus** 2015-07-29 20:56 UTC
