### ISSUE TITLE
Duplicate project names

### ISSUE THREAD

**Issue by tangerine007** [projectjellyfish/api#503] opened 2015-04-10 20:00 UTC
Should the user be allowed to have duplicate project names?
![image](https://cloud.githubusercontent.com/assets/4211939/7095721/a08f8152-df9a-11e4-85b1-5dfc7bb29095.png)

**Comment by chriskacerguis** [comment] 2015-04-10 20:07
I think that this is ok, it's not ideal, but I can see situations where a large company could have multiple project with the same name, but not the same people.

@sonejah21 thoughts?

**Comment by AllenBW** [comment] 2015-04-10 21:03
So if not by name what would the laymen/quick to say unique identified for
a project?  maybe the compromise is notify a user that the name is already
used and suggest they alter it when creating a new project.

**Comment by sonejah21** [comment] 2015-04-10 21:46
@tangerine007 - So if I understand this ticket correctly, the issue is that it is possible to create multiple projects with the same exact Project Name and this could be confusing. Is that right? 

@AllenBW - I agree with the suggestion to create a unique name.
Generally when dealing with purchases like many projects will be dealing with, I'd say the less confusion, the more precision, the better. Since some projects and companies will be dealing with multiple large purchases within their different projects, we can't afford to having the name game to blame (like that rhyme?!). 

We can even take it a step further and include a tip in the UI when creating a new project that suggests a specific name, giving an example. That way the user is set up to succeed at their first try instead of getting them frustrated when they can't choose "Project 1" or "Mobile App Project" or other generic titles.

@chriskacerguis - are you cool with feel requiring unique project names?

**Comment by chriskacerguis** [comment] 2015-04-10 22:41
@sonejah21 I'm still not sold (open, but not sold), for 2 reasons:

1.  There is a minor technical challenge of "enforcing" the unique names.  For example:
````
"My Project"
and
"My Project "
````
Note the extra [space] in the 2nd thing.  That's easily "fixable", but then we introduce, what I like to call the "World of Warcraft" name problem.

````
"My Project"
"mY pROJECT"
"my project"
"My pr0j3ct"
"My_Project_"
````
You get the idea.  Yes, each one unique, but...you know...damn.

Perhaps it would be better to having some sort of better unique key?  A project code perhaps that would be unique?  So...

My Project would become "mypro" 
The next person that tries to create My Project, it would then flag the new "mypro" as non-unique and then force the user to do a new unique code, but still keeping the title.

Then display it as
````
[project_code] Project Title
````

@sonejah21 @tangerine007 @AllenBW thoughts?

**Comment by chriskacerguis** [comment] 2015-04-30 17:58
Closing.  No additional thoughts, so we'll leave it the way it is.

**Closed** 2015-04-30 17:58 UTC
