### ISSUE TITLE
Create UX to view all servers

### ISSUE THREAD

**Issue by chriskacerguis** [projectjellyfish/api#477] opened 2015-04-06 13:35 UTC
Need a UX that would allow someone to see all servers (regardless of project) that they have access to.  This would be a new "tab" on the side bar called "servers"

**Comment by sonejah21** [comment] 2015-04-07 21:45
- Added "My Services" to sidebar. 
- Got the specific Products to load, but am working with Michael to create the new API endpoints for "Servers" and other product types to reside inside of My Services.

![uploads/db33065d-4090-4357-a512-d944128f2d83/Screen Shot 2015-04-07 at 5.43.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fdb33065d-4090-4357-a512-d944128f2d83%2FScreen+Shot+2015-04-07+at+5.43.22+PM.png)

**Comment by chriskacerguis** [comment] 2015-04-07 22:07
I'm wondering if they tree is something we should hold off on, that seems like it would be very long, very quick?  Also, thinking out loud about what kind of icon we can use for the "My Services" button.

Thoughts?

**Comment by sonejah21** [comment] 2015-04-07 23:10
The above snapshot is not yet accurate. I wanted to ensure that I could get some products flowing into the My Services. Michael is working on the new API endpoint. Eventually the list of Services here will be product types listed, of which there are fewer. 

The icon for "My Services":  What does the tachometer icon represent in the project cards currently? If that represents the services a project has, then we can use that. But since I am not sure, and I think that there is a server icon next to the tachometer, here are my other suggestions apart from what has already been used:

![uploads/fa3f3c9f-799b-494e-8447-5329eeadc2de/Screen Shot 2015-04-07 at 7.02.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ffa3f3c9f-799b-494e-8447-5329eeadc2de%2FScreen+Shot+2015-04-07+at+7.02.08+PM.png)
- Plain and simple, a list of items. (Not my first choice). 

![uploads/f362af5d-9f16-4db5-8029-3e333b99fe21/Screen Shot 2015-04-07 at 7.00.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff362af5d-9f16-4db5-8029-3e333b99fe21%2FScreen+Shot+2015-04-07+at+7.00.08+PM.png)
- Multiple gears look more like cogs of a watch, all working together to create a functioning application.

![uploads/7a12f229-51af-44d0-bb48-5f2f1d3308b4/Screen Shot 2015-04-07 at 7.00.27 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7a12f229-51af-44d0-bb48-5f2f1d3308b4%2FScreen+Shot+2015-04-07+at+7.00.27+PM.png)
- Representing the "exchange of services". (Get it?!)

**Comment by chriskacerguis** [comment] 2015-04-07 23:17
Well, we need to look at the cards and those symbols...

BUT, I think that the tachometer should be the Dashboard.  

What about this?

http://fortawesome.github.io/Font-Awesome/icon/cubes/

Services are "building blocks"?

**Comment by sonejah21** [comment] 2015-04-08 15:29
Yeah, that makes sense. I like the lovely cubes icon for Services. They're also used here to a more graphic degree, but we'll be changing the look of this eventually. 
![uploads/b38d015a-cda9-4293-bf4d-61e45640c761/Screen Shot 2015-04-08 at 11.24.37 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb38d015a-cda9-4293-bf4d-61e45640c761%2FScreen+Shot+2015-04-08+at+11.24.37+AM.png)

**Comment by sonejah21** [comment] 2015-04-09 20:03
Temporarily assigned this to Michael, since the API is in progress. When he's done, I'll take it back.

**Comment by AllenBW** [comment] 2015-04-14 14:20
like chalk on a board.

On Tue, Apr 14, 2015 at 10:11 AM, Michael Fernando <notifications@github.com

**Comment by sonejah21** [comment] 2015-04-29 02:18
hey @mafernando - let me know if/when the Services page is ready for some UX love :heart: and I'll toss in the styling for the project cards!

**Comment by chriskacerguis** [comment] 2015-06-30 13:07
@AllenBW is this done?

**Comment by AllenBW** [comment] 2015-06-30 13:12
yep.  services view accessed from left nav breaks all existing services (ie
products in motion) out by type... of note, you cannot access a service's
details from this page, only from the service listing on a project page
(this is intentional)

**Comment by AllenBW** [comment] 2015-06-30 16:00
I should clarify though, we still require a new nav bar icon for this page presently its a duplicate of the admin gear.... give me this icon and we'll close this champ

**Comment by AllenBW** [comment] 2015-07-01 19:45
added services icon, will show up when enhancement/388 is merged, closing this now

**Closed by AllenBW** 2015-07-01 19:45 UTC
Labels: enhancement, ux
